const fs = require('fs').promises;
const pdfModule = require('pdf-parse'); 
const pdfParse = pdfModule.default || pdfModule; 
const { GoogleGenAI } = require('@google/genai'); 
require('dotenv').config(); 

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
const model = 'gemini-2.0-flash'; 

const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

async function generateMetadata(fileBuffer) {
  
  const prompt = `Analyze this PDF research paper (including text and visual diagrams/images). 
    
    1. Extract Metadata:
       - Exact Title: The full, exact title of the paper.
       - Primary authors: List of strings (Full names).
       - Keywords: List of EXACTLY 6 strings.
         * The first 4 keywords must be terms found explicitly in the abstract of the paper.
         * The last 2 keywords must be generated by you (broader themes or inferred topics from the analyzed paper).
         * IMPORTANT: Each keyword must be EXACTLY ONE WORD (no spaces).
       - Publication Date: YYYY-MM-DD or YYYY.
       - The Journal/Conference Name. Use "Unknown Source" if not found.
       - Abstract: If the paper contains an "Abstract" section, extract the text from it verbatim. If no Abstract section exists, generate a concise summary (100-150 words) of the paper.
    
    2. Content Safety & Validity Check:
       - Review the document for hate speech, harassment, and dangerous content.
       - Review ALL IMAGES and FIGURES for explicit sexual content, gore, or inappropriate symbols.
       - **Empty Document Check**: Verify if the document contains meaningful content (text or research diagrams). 
         * If the document appears to be blank (white pages), contains only random noise, or has absolutely no readable text/content, consider it invalid.
       - Set 'is_safe' to false if ANY text/image violates policies OR if the document is empty/blank.
       - Safety Reason: If unsafe, provide a specific explanation (e.g., "Contains explicit nudity" or "Document appears to be empty/blank").
       - **NOTE**: If the document is empty/invalid, you may fill the required Metadata fields (Title, Authors, etc.) with "N/A" or generic placeholders to satisfy the JSON schema.
    
    Return JSON.`;

  const maxRetries = 3;
  let lastError;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const response = await ai.models.generateContent({
        model: model,
        contents: [
          {
            role: 'user',
            parts: [
              { text: prompt },
              {
                inlineData: {
                  mimeType: "application/pdf",
                  data: fileBuffer.toString("base64")
                }
              }
            ]
          }
        ],
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: "object",
            properties: {
              ai_title: { type: "string" },
              ai_authors: { type: "array", items: { type: "string" } },
              keywords: { type: "array", items: { type: "string" } }, 
              ai_date_created: { type: "string" },
              ai_journal: { type: "string" },
              ai_abstract: { type: "string" },
              is_safe: { type: "boolean" },
              safety_reason: { type: "string" }
            },
            required: ["ai_title", "ai_authors", "keywords", "ai_date_created", "ai_journal", "ai_abstract", "is_safe", "safety_reason"],
          },
        },
      });
      
      return JSON.parse(response.text);

    } catch (err) {
      lastError = err;
      if (err.message && (err.message.includes("overloaded") || err.status === 503)) {
        await delay(2000 * attempt);
        continue;
      }
      break; 
    }
  }
  throw lastError;
}

exports.analyzeDocument = async (fileBuffer) => {
  try {
    const data = await pdfParse(fileBuffer); 
    const rawText = data.text; 
    const numPages = data.numpages;

    if (!numPages || numPages === 0) {
        return {
            title: "Invalid Document",
            ai_keywords: "[]",
            ai_authors: "[]",
            ai_date_created: "N/A",
            ai_journal: "N/A",
            ai_abstract: "N/A",
            is_safe: false,
            safety_reason: "The document is invalid (contains 0 pages)."
        };
    }

    console.log(`[AI Service] Text parsed (${rawText.length} chars). Executing Hybrid Analysis...`);

    const metadata = await generateMetadata(fileBuffer);
    
    return {
        title: metadata.ai_title,
        ai_keywords: JSON.stringify(metadata.keywords),
        ai_authors: JSON.stringify(metadata.ai_authors),
        ai_date_created: metadata.ai_date_created,
        ai_journal: metadata.ai_journal,
        ai_abstract: metadata.ai_abstract,
        is_safe: metadata.is_safe,           
        safety_reason: metadata.safety_reason 
    };
  } catch (err) {
    console.error("[AI Service] Error:", err.message);
    throw err; 
  }
};

exports.formatCitation = async (docData, style) => {
  const prompt = `
    You are a bibliographer. Format the following research paper metadata into a perfect ${style} citation. 
    Return ONLY the citation string. No explanations.
    
    Metadata:
    Title: ${docData.title}
    Authors: ${docData.authors}
    Date: ${docData.date}
    Journal: ${docData.journal}
  `;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: [{ role: 'user', parts: [{ text: prompt }] }]
    });
    
    return { citation: response.text ? response.text.trim() : "" };
  } catch (err) {
    console.error("Citation Error:", err);
    throw new Error("Failed to generate citation");
  }
};

exports.generateGraphDescription = async (graphData) => {
  const prompt = `
    You are a data analyst for ArchiviaCMS. 
    Analyze the following dataset representing system activity (e.g., uploads, active users over time).
    
    Data:
    ${JSON.stringify(graphData)}

    Provide a concise, insight-driven description (max 50 words). 
    Focus on:
    1. Identifying the peak month/period.
    2. Noting any significant trends (upward/downward).
    3. Suggesting a potential cause or action (e.g., "Increase storage during peak months").
    
    Output: Plain text only.
  `;

  const maxRetries = 3;
  let lastError;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const response = await ai.models.generateContent({
        model: model,
        contents: [{ role: 'user', parts: [{ text: prompt }] }]
      });
      
      return response.text ? response.text.trim() : "No analysis generated.";
    } catch (err) {
      lastError = err;
      if (err.message && (err.message.includes("overloaded") || err.status === 503)) {
        await delay(2000 * attempt);
        continue;
      }
      console.error("[AI Service] Graph analysis failed:", err.message);
      break; 
    }
  }
  return "Unable to generate graph analysis at this time.";
};

// --- FIX: Corrected this function to use ai.models.generateContent ---
exports.generateDashboardInsight = async (data) => {
  try {
    const prompt = `
      You are a Data Analyst for a research archive. Analyze the following system statistics and write a short, professional executive summary (max 10 sentences and 100 words) suitable for a printed report.
      
      Data:
      - Total Documents: ${data.totalDocuments}
      - Total Users: ${data.totalUsers}
      - Top Search Terms: ${data.topSearches.map(s => s.term).join(', ')}
      - Recent Upload Activity (Month: Count): ${data.uploadTrend.map(t => `${t.month}: ${t.count}`).join(', ')}
      - Top Research Topics: ${data.topKeywords.map(k => k.term).join(', ')}

      Focus on the trends and most active research areas. Do not use markdown or bullet points, just a paragraph.
    `;

    // Updated Syntax for @google/genai
    const response = await ai.models.generateContent({
      model: model,
      contents: [{ role: 'user', parts: [{ text: prompt }] }]
    });

    return response.text ? response.text.trim() : "Analytics data is available for review in the charts below.";

  } catch (error) {
    console.error("AI Insight Error:", error);
    return "Analytics data is available for review in the charts below.";
  }
};